version: '3.4'
services:
    jupyter-notebook:
        build:
          context: .
          dockerfile: Dockerfile
          args:
            JUPYTER_TOKEN: '${CONTAINER_TOKEN}'
        volumes:
            - /tmp/jupyter_test_dir:/home/jupyter 
        ports:
            - ${CONTAINER_PORT}:8888
        container_name: ${CONTAINER_NAME}
        command: "--allow-root"
        healthcheck:
          test: "exit 0"
          interval: 4s
          timeout: 5s
          retries: 1